Revert "Use gcc 10.2 where possible to build and run s390 images"
This reverts commit 3d940562a8fbe831ff6813306dcb933d4ed5b6dd.

s390 doesn't build with gcc 10.2 at least up to v5.4.y.

arch/s390/include/asm/atomic_ops.h:46:2: error: impossible constraint in 'asm'

Revert to gcc 8.3.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>