rootfs: ppc64: Replace CONFIG_TICK_CPU_ACCOUNTING with CONFIG_VIRT_CPU_ACCOUNTING_NATIVE
CONFIG_TICK_CPU_ACCOUNTING results in a build error in mainline (v4.8-rc1+).

In file included from ./arch/powerpc/include/asm/mmu_context.h:11:0,
                 from ./include/linux/mmu_context.h:4,
		 from mm/mmu_context.c:8:
./arch/powerpc/include/asm/cputhreads.h: In function 'get_tensr':
./arch/powerpc/include/asm/cputhreads.h:101:2: error:
	implicit declaration of function 'cpu_has_feature'

Since it's unclear if the fix for that will be accepted upstream,
bypass it to prevent other problems from sneaking in.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>