rootfs: ppc64: Enable CONFIG_DTL=y
CONFIG_DTL=y is now required to avoid the following build failure.

arch/powerpc/kernel/irq.o: in function `.do_IRQ':
irq.c:(.text+0x2798): undefined reference to `.pseries_accumulate_stolen_time'

Signed-off-by: Guenter Roeck <linux@roeck-us.net>