stable-build-target: Drop perf builds for 6.1.y
perf does not build in 6.1.y on Ubuntu 24.04.
Error message:

tests/bpf.c: In function ‘epoll_pwait_loop’:
tests/bpf.c:36:17: error: argument 2 null where non-null expected [-Werror=nonnull]
   36 |                 epoll_pwait(-(i + 1), NULL, 0, 0, NULL);

Ubuntu 24.04 uses glibc 2.39, which indeed does a parameter check on
epoll_pwait() and rejects calling it with NULL as second parameter.

Don't bother trying to fix the problem, just stop build testing perf
on 6.1.y kernels.

Note: The problems are not seen in v6.6+. The offending file and
functionality have been removed with upstream commit 3d6dfae88917
("perf parse-events: Remove BPF event support").

Signed-off-by: Guenter Roeck <linux@roeck-us.net>