stable-build-arch: Clarify that parisc needs gcc 12.x for v6.4+
The latest mainline kernel (as of v6.9-8435-g62f87872a95e)
fails to build parisc:allmodconfig.

drivers/gpu/drm/nouveau/nvif/object.c: In function 'nvif_object_mthd':
drivers/gpu/drm/nouveau/nvif/object.c:161:9: error: 'memcpy' accessing 4294967264 or more bytes at offsets 0 and 32 overlaps 6442450881 bytes at offset -2147483617 [-Werror=restrict]
  161 |         memcpy(data, args->mthd.data, size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/nouveau/nvif/object.c: In function 'nvif_object_ctor':
drivers/gpu/drm/nouveau/nvif/object.c:298:17: error: 'memcpy' accessing 4294967240 or more bytes at offsets 0 and 56 overlaps 6442450833 bytes at offset -2147483593 [-Werror=restrict]
  298 |                 memcpy(data, args->new.data, size);

This is seen with gcc 12.x and later. Add comment explaining that parisc
needs at least gcc 12.x to build and that trying to build with an earlier
version of gcc is not an option.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>